import { ethers, run, network } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`\n🚀 Deploying SplitBase on ${network.name}`);
  console.log(`   Deployer: ${deployer.address}`);
  console.log(
    `   Balance : ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`
  );

  const Factory = await ethers.getContractFactory("SplitBase");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`✅ SplitBase deployed at: ${address}`);
  console.log(`   Tx hash: ${contract.deploymentTransaction()?.hash}\n`);

  // Write address to a file the frontend can read
  const fs = await import("fs");
  const path = await import("path");
  const outPath = path.resolve(__dirname, "../frontend/lib/contract-address.ts");
  fs.writeFileSync(
    outPath,
    `// Auto-generated by deploy script — do not edit manually\nexport const CONTRACT_ADDRESS = "${address}" as const;\n`
  );
  console.log(`📝 Contract address written to frontend/lib/contract-address.ts`);

  // Verify on Basescan (skip on localhost)
  if (network.name !== "hardhat" && network.name !== "localhost") {
    console.log("\n⏳ Waiting 5 confirmations before verification...");
    await contract.deploymentTransaction()?.wait(5);

    try {
      await run("verify:verify", { address, constructorArguments: [] });
      console.log("✅ Contract verified on Basescan");
    } catch (e: any) {
      if (e.message.includes("Already Verified")) {
        console.log("ℹ️  Already verified");
      } else {
        console.warn("⚠️  Verification failed:", e.message);
      }
    }
  }

  console.log("\n─────────────────────────────────────────────────");
  console.log("NEXT STEPS:");
  console.log(`  1. Add to .env.local: NEXT_PUBLIC_CONTRACT_ADDRESS="${address}"`);
  if (network.name === "base-sepolia") {
    console.log(
      `  2. View on Basescan: https://sepolia.basescan.org/address/${address}`
    );
  }
  console.log("─────────────────────────────────────────────────\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
